{% set name = "msrestazure" %}
{% set version = "0.6.0" %}
{% set sha256 = "99b185dcfc94f4ac2f7792691b865958c5a9871281cd618c50963c6b8d23401b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - msrest >=0.4.25
    - keyring >=5.6
    - adal >=0.5.0
    
test:
  imports:
    - msrestazure
    - msrestazure.azure_active_directory
    - msrestazure.azure_exceptions
    - msrestazure.azure_operation

about:
  home: https://github.com/Azure/msrestazure-for-python
  license: MIT
  license_family: MIT
  summary: The runtime library "msrestazure" for AutoRest generated Python clients
  
extra:
  recipe-maintainers:
    - ivoflipse
