{% set name = "msrestazure" %}
{% set version = "0.4.26" %}
{% set sha256 = "ab49c00b53b089713fc9e0176b2420be90a1c8583a45f58eb0d8252b1d414f4c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - msrest >=0.4.25
    - keyring >=5.6
    - adal >=0.5.0
    
test:
  imports:
    - msrestazure
    - msrestazure.azure_active_directory
    - msrestazure.azure_exceptions
    - msrestazure.azure_operation

about:
  home: https://github.com/Azure/msrestazure-for-python
  license: MIT
  license_family: MIT
  summary: The runtime library "msrestazure" for AutoRest generated Python clients
  
extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
