travis:
  secure:
    BINSTAR_TOKEN: LcDly8AvFOEG0baSwE2Z+7m1jw+Zd2Fhnt01CBjKklNENTeUCxsv74FyQtezHvuAYxx17ExBN3PLdWooZuaPyWCwUipAkFVhwY7XVoX11bM0dT6g9lxapJnc0sbF0vT7dlk8Tlt1aQIcLo0ON9Mc9zq7hb7Yt9VH/4HRA52AKzGDk2SqN5dGux2ddbetO/35tHZrUKaR1JzpdUYXxueomTU83nYiS1vZYDM3bHeOnkcgLCBrxkFO2C18EJQXgzSO1FiQdq2THW6SasVfxKkBqMtHwArwrqDLLW26mpA1SVfQa2AVMzTIUn7e3ObIsTRMgU82QtkL6Xg60nygpj2U07wP+SjHo52YUIOr9F07PRwVTQE7aNrhzHLTK7D2Yf2VKF0gxTLT2xcU6jp86tgvb50UszAldHTumJy4+iM46rGfNLpDE2YfKkFGw+R0+/g+fh6Id1HQsaNeGubhXv9VSucl/Iwdh4rvbkeFt+x+AGR4dYXdvZOHxGW6xvDKOmJ5rfFYduo8/+2naZMRk523YQNnqyj5oij/Q6BtLGc+lZmLGfFqOmTakd4cSRD791JuYT4unIFI6Alob0tV9RXtXKQ2y8pLyWrtMCTbQU842qVvAQRe1o9ZN9L3ZGrwr7xpXRt2zBMtn5qxSpbDwC5mrG9ds/IK1+NPNBYzOEkBMJc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
