travis:
  secure:
    BINSTAR_TOKEN: g3MW9Bay3r6jV89LX2NTehyWShh++Xuex3WZUlIkFHcqTA+B5xWnxInUIqCO/Yxz3RkU9Z/+TB5xLhubhV3/c9nub426zpBG/pxARxGuf8BV0M3aqr10b1hqbYPFtEwOMjOdUNwZJ//PFKVAVgUJzy+7vt3ha/0SIPpU4W+slhESmXWLnxtzPSNimMEEtzqVMaYqBlrfvPynJGiZ9hHSmQSPu7Ng9iIXExL+EREsw7DSHcdGl7bUNdjhcng326uzN8MMNBMrQTRC3FRmcchXKWzRZM09/ocy9EKbtjo6GkxpqyLFvT5Ep7pklQnU61MOg9x3fIckCwhAnov8Jk4ENljYNA1d6/z4Z9YQHGBbUK4OxljJGw2xxshTKvLFDSV6MWYOWQ2El6DcTwREf8VBYWUx8HP1Gy2wkxmgi4doZwgo4D1FUJFWHQ5rSCB7jI8L4cLX+R7QPY0Q/tW/JcnjXnJuslmlHmhLRki4fCyumekoKaOFmG0+6NITQk/Edo3ncdp6PWnr+ycc/B6aRegUPyU969VVQQRVRR0+GOX/wWkS+iBhIT9UDykNfy4vw458njCAC7u/8kvq4rSz72pdXvDhjaCWlZnOlEBT6DH5jguQe5ePHFvnZ31FESETl1B0P7wNtGl/aZ/ik32QfD2GWWEDUQS3TAb8d69VTNOBgus=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
